In [ ]:
Author:  Sachin Baburao Shelke

In [ ]:
Supervised Machine Learning

Linear Regression Algorithm

In [152]:
import numpy as np

In [153]:
x = np.arange(1,25).reshape(12,2)
y = np.array([0,1,1,1,0,0,0,0,1,1,0,1])

In [154]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [155]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1])

In [156]:
len(y)

12

In [157]:
len(x)

12

In [ ]:
Training Data 
Validation Data
Test Data

In [ ]:
Split the data

In [158]:
from sklearn.model_selection import train_test_split

In [159]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [160]:
x_train

array([[17, 18],
       [11, 12],
       [15, 16],
       [19, 20],
       [ 3,  4],
       [21, 22],
       [ 9, 10],
       [13, 14],
       [ 5,  6]])

In [161]:
x_test

array([[23, 24],
       [ 1,  2],
       [ 7,  8]])

In [162]:
len(x_train)

9

In [163]:
y_test

array([1, 0, 1])

In [164]:
y_train

array([1, 0, 0, 1, 1, 0, 0, 0, 1])

In [165]:
len(y_train)

9

In [166]:
x_train,x_test,y_train,y_test=train_test_split(x,y, random_state=100)

In [167]:
x_train

array([[11, 12],
       [ 9, 10],
       [ 5,  6],
       [ 1,  2],
       [21, 22],
       [15, 16],
       [ 7,  8],
       [23, 24],
       [17, 18]])

In [168]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 1, 1])

In [169]:
x_test

array([[19, 20],
       [13, 14],
       [ 3,  4]])

In [170]:
y_test

array([1, 0, 1])

In [171]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30 ,random_state=100)

In [172]:
x_train

array([[ 9, 10],
       [ 5,  6],
       [ 1,  2],
       [21, 22],
       [15, 16],
       [ 7,  8],
       [23, 24],
       [17, 18]])

In [173]:
len(x_train)

8

In [174]:
len(x_test)

4

In [175]:
len(y_train)

8

In [176]:
len(y_test)

4

In [177]:
import numpy as np

In [178]:
from sklearn.linear_model import LinearRegression

In [179]:
x = np.arange(20).reshape(-1,1) 

In [180]:
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [181]:
y = np.array([5,12,11,19,30,29,23,40,51,54,74,62,68,73,89,84,89,101,99,106])

In [182]:
y

array([  5,  12,  11,  19,  30,  29,  23,  40,  51,  54,  74,  62,  68,
        73,  89,  84,  89, 101,  99, 106])

In [183]:
len(x)

20

In [184]:
len(y)

20

In [185]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=8, random_state=30)

In [186]:
x_train

array([[16],
       [ 3],
       [ 1],
       [18],
       [ 2],
       [ 7],
       [12],
       [ 4],
       [17],
       [13],
       [19],
       [ 5]])

In [187]:
y_train

array([ 89,  19,  12,  99,  11,  40,  68,  30, 101,  73, 106,  29])

In [188]:
len(x_train)

12

In [189]:
len(x_test)

8

In [190]:
len(x)

20

In [191]:
model = LinearRegression()

In [192]:
model.fit(x_train,y_train)

LinearRegression()

In [193]:
# y = mx + c

In [194]:
model.intercept_

3.69925925925925

In [111]:
model.coef_

array([5.40691358])

In [ ]:
# y = mx + c
y = 5.40691358x + 3.69925925925925

In [195]:
x_test

array([[11],
       [ 0],
       [15],
       [14],
       [ 9],
       [ 6],
       [10],
       [ 8]])

In [113]:
model.predict(x_test)

array([63.17530864,  3.69925926, 84.80296296, 79.39604938, 52.36148148,
       36.14074074, 57.76839506, 46.9545679 ])

In [196]:
model.score(x_train, y_train)*100

99.43001045262282

In [197]:
model.score(x_test, y_test)*100

90.73311099207432

In [198]:
model_prediction = model.predict(x_test)

In [199]:
model_prediction

array([63.17530864,  3.69925926, 84.80296296, 79.39604938, 52.36148148,
       36.14074074, 57.76839506, 46.9545679 ])

In [200]:
import pandas as pd

In [201]:
x1 = pd.DataFrame(x, columns=['x'])

In [202]:
y1 = pd.DataFrame(y , columns=['y-actual'])

In [203]:
df = pd.concat([x1,y1] , axis=1)

In [204]:
df

x  y-actual
0    0         5
1    1        12
2    2        11
3    3        19
4    4        30
5    5        29
6    6        23
7    7        40
8    8        51
9    9        54
10  10        74
11  11        62
12  12        68
13  13        73
14  14        89
15  15        84
16  16        89
17  17       101
18  18        99
19  19       106

In [215]:
model_prediction=model.predict(x)

In [216]:
y_predictions = pd.DataFrame(model_prediction, columns=['y_predicted'])

In [217]:
df = pd.concat([df,y_predictions], axis=1)

In [218]:
df

x  y-actual  y_predicted
0    0         5     3.699259
1    1        12     9.106173
2    2        11    14.513086
3    3        19    19.920000
4    4        30    25.326914
5    5        29    30.733827
6    6        23    36.140741
7    7        40    41.547654
8    8        51    46.954568
9    9        54    52.361481
10  10        74    57.768395
11  11        62    63.175309
12  12        68    68.582222
13  13        73    73.989136
14  14        89    79.396049
15  15        84    84.802963
16  16        89    90.209877
17  17       101    95.616790
18  18        99   101.023704
19  19       106   106.430617

In [ ]:
#Logistic Regression